name: guess-mime

env:
  guess-mime-version: 1.0.0

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=0 --disable-warnings -q

      - name: Lint Python code
        run: |
          pip install flake8
          flake8 guess_mime tests --max-line-length=128

      - name: Type checking with mypy
        run: |
          pip install mypy
          mypy guess_mime

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      - name: Build executable with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile guess_mime/guess_mime.py
          
      - name: Find and copy built executable
        run: |
          # Use `find` to dynamically locate the built executable in the dist folder
          EXECUTABLE=$(find dist -type f -name "guess-mime" -executable)
          if [[ -n "$EXECUTABLE" ]]; then
            echo "Found executable at $EXECUTABLE"
            # Upload the found executable as an artifact
            mkdir -p output
            cp "$EXECUTABLE" output/"${EXECUTABLE}-${GUESS_MIME_VERSION}"
            echo "Executable copied to output directory"
          else
            echo "Error: Executable not found!"
            exit 1
          fi
        env:
          GUESS_MIME_VERSION: ${{ env.guess-mime-version }}
      
      - name: Upload built executable as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: guess-mime  
          path: output/ 
